// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx03WhrjQCYeEVMVt7nVKluIS9u_xTD44',
    appId: '1:647539702543:web:d55bd8849267470526dc7a',
    messagingSenderId: '647539702543',
    projectId: 'burger-buzz-2e026',
    authDomain: 'burger-buzz-2e026.firebaseapp.com',
    storageBucket: 'burger-buzz-2e026.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs-6Pbzh2U_yPy0buuRjO2WzYRwYmOj8s',
    appId: '1:647539702543:android:841331281ace424926dc7a',
    messagingSenderId: '647539702543',
    projectId: 'burger-buzz-2e026',
    storageBucket: 'burger-buzz-2e026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_mzrpvV-wbi_N_gUL2aYSjGUTznS3jE',
    appId: '1:647539702543:ios:d42d404213f7fb8926dc7a',
    messagingSenderId: '647539702543',
    projectId: 'burger-buzz-2e026',
    storageBucket: 'burger-buzz-2e026.appspot.com',
    iosBundleId: 'com.example.burgerBuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo_mzrpvV-wbi_N_gUL2aYSjGUTznS3jE',
    appId: '1:647539702543:ios:69034fb8b1e4564f26dc7a',
    messagingSenderId: '647539702543',
    projectId: 'burger-buzz-2e026',
    storageBucket: 'burger-buzz-2e026.appspot.com',
    iosBundleId: 'com.example.burgerBuzz.RunnerTests',
  );
}
